### ISSUE TITLE
Visualizar detalhes da comunicação do evento

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/zerobito#25]
Eu como um profissional da segurança do trabalho gostaria de visualizar as informações da comunicação de um evento no Painel de Controle de forma que eu possa decidir sobre aceitá-lo como caso ou não incorporar a denúncia com base em mais informações.

Critérios de Aceitação

- Verificar se é possível visualizar a Data e Local (Logradouro, Cidade e Estado) do Evento; (pass)
- Verificar se é possível visualizar um evento sem data e local; (fail)
- Verificar se o evento tem status "Aguardando análise"; (pass)
- Verificar se o evento tem outro status qualquer; (fail)
- Verificar se é possível visualizar opcionalmente o nome da vítma; (pass)
- Verificar se é possível visualizar opcionalmente o nome da empresa empregadora e CPNJ; (pass)
- Verificar se é possível visualizar opcionalmente o nome da tomadora de serviço e CPNJ; (pass)
- Verificar se é possível visualizar opcionalmente o vínculo da vítma com empresa; (pass)
- Verificar se é possível visualizar o tipo (Anônimo, Vítma, Familiar, Colega de Trabalho, Sindicato, Imprensa, Serviços de Saúde, Outros (especificar)), nome, e-mail, telefone (duas opções) e endereço da Fonte de Informações da Ocorrência (pass)
- Verificar se o tipo for Anônimo, os demais campos (nome, e-mail, telefone (duas opções) e endereço da Fonte) devem estar ausentes;
- Verificar se é possível visualizar as condições da vítma (Óbito ou Incidente com Alto Potencial, sendo o último com uma escala de gravidade associada: Emergencial, Muito Urgente, Urgência, Pouca Urgência).

História do Épico #5

**Comment by lhleonardo** [comment]
Iniciando a análise técnica para verificar a questão da tabela com conteúdo expansível e ordenações.
