### ISSUE TITLE
Localização do caso

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/zerobito#42]
Eu como profissional da segurança do trabalho ou membro do grupo de trabalho gostaria de visualizar a localização do caso no dossie, de forma que identifique rapidamente o local da ocorrência

Critérios de Aceitação

- Verifcar se, ao aceitar a comunicação como caso, a localização do caso no dossiê é igual a localização informada na comunicação do evento; (pass)
- Verificar a localização está em branco ou vazia; (fail)

Referência para componente de mapa: https://react-leaflet.js.org/

História do Épico: #37

**Comment by lhleonardo** [comment]
feito no PR https://github.com/SocialSoftwareLivingLab/zerobito/pull/61
