### ISSUE TITLE
Registro Básico do Evento

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/zerobito#6]
Eu como um profissional da segurança do trabalho gostaria de registrar as informações básicas de um evento (ocorrência de acidente de trabalho) de forma que o mesmo possa ser qualificado.

**Critérios de Aceitação**

- Verificar se é possível informar a Data e Local (Logradouro, Cidade e Estado) do Evento; (pass)
- Verificar se é possível registrar um evento sem data e local; (fail)
- Verificar se o evento é registrado com status "Aguardando análise"; (pass)
- Verificar se o evento é registrado com outro status qualquer; (fail)
- Verificar se é possível informar opcionalmente o nome da vítma; (pass)
- Verificar se é possível informar opcionalmente o nome da empresa empregadora e CPNJ; (pass)
- Verificar se é possível informar opcionalmente o nome da tomadora de serviço e CPNJ; (pass)
- Verificar se é possível informar opcionalmente o vínculo da vítma com empresa; (pass)
- Verificar se é possível informar **opcionalmente** o tipo (Anônimo, Vítma, Familiar, Colega de Trabalho, Sindicato, Imprensa, Serviços de Saúde, Outros (especificar)), e um campo aberto para **Informações Adicionais**
- Verificar se o tipo for Anônimo, os demais campos (nome, e-mail, telefone (duas opções) e endereço da Fonte) devem estar desabilitados;
- Verificar se é possível informar as condições da vítma (**Óbito, Atendimento Hospitalar, Incidente de Alto Potencial**).

História do Épico #5

**Comment by lhleonardo** [comment]
Entregue
