### ISSUE TITLE
Iniciar Planejamento

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/zerobito#74]
Eu como coordenador de caso gostaria de iniciar a fase de planejamento de forma que que todos os membros do grupo de trabalho estejam cientes de que devem atuar no plano de investigação

Critérios de Aceite

* O estado do caso deve estar "Em Preparação" (_pass_);
* O estado do caso está diferente de "Em Preparação" (_fail_): Mensagem de erro: "O planejamento ainda não pode ser iniciado.";
* O estado do caso está como "Aguardando Notificações" (estado de criação do caso), e opção de Iniciar Planejamento está habilitada (_fail_).
* Encaminhar para a primeira reunião. (pass)

História do Épico #73 

Notas: 
Estados do caso: aguardando notificações --> em preparação --> em planejamento

**Comment by lhleonardo** [comment]
Primeira etapa feita em https://github.com/SocialSoftwareLivingLab/zerobito/pull/89
