### ISSUE TITLE
Cancelar aceite de caso

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/zerobito#80]
No aceite do caso, inserir uma opção de "Cancelar" para voltar ao Painel de Controle.
![image](https://github.com/user-attachments/assets/373fe2c6-8f39-49bc-86eb-78581687b72a)

**Comment by lhleonardo** [comment]
feito no PR https://github.com/SocialSoftwareLivingLab/zerobito/pull/89
![image](https://github.com/user-attachments/assets/e73a340d-9c7c-4d4a-91c9-15719301b38a)
